name: make-github-release-assets.yaml

on: [push]

# on:
#   push:
#     tags:
#       - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Publish binaries
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Make RPM/DEB files
        run: make package

      - name: install create-dmg
        run: brew install create-dmg
      - run: pwd
      - run: mkdir output
      - run: cd output
      - name: Did a file get created (before)
        run: ls -la output
      - run: echo "Test file" > output/bob.txt
      - name: Make a .dmg file
        run: create-dmg  --app-drop-link 0 40 "MJD-Application-Installer.dmg"  "output/"
      - name: Did a file get created (after)
        run: ls -la output
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /Users/runner/work/test-ground/test-ground/MJD-Application-Installer.dmg
          asset_name: bob7.dmg
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
